# Generated by Django 6.0.7 on 2026-09-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustbins', '0002_dustbin_is_full_alter_dustbin_dustbin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbin',
            name='last_priority_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dustbin',
            name='priority_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='dustbin',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
    ]
