# Generated by Django 6.0.7 on 2026-09-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustbins', '0003_dustbin_last_priority_update_dustbin_priority_level_and_more'),
    ]

    operations = [
       migrations.AddField(
    model_name='dustbin',
    name='bin_id',
    field=models.CharField(
        blank=True,
        editable=False,
        max_length=20,
        null=True,
    ),
),
        migrations.AddField(
            model_name='dustbin',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='dustbin_qr/'),
        ),
    ]
