# Generated by Django 6.0.7 on 2026-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustbins', '0004_dustbin_bin_id_dustbin_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dustbin',
            name='bin_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
