# Generated by Django 6.0.7 on 2026-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastescan',
            name='co2_emission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='wastescan',
            name='danger_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
    ]
